@echo off
REM HENRY hermes wrapper — Windows shim that calls the bash launcher via WSL
REM Generated by hermesify.py
wsl.exe -d Ubuntu -- bash -lc "cd '/mnt/c/Users/whitt/Development/henry-consulting' && ./hermes %*"
